package com.boc.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("doctorinfo", "doctor_id", Doctorinfo.class);
		// Composite Primary Key order: city_code,country_code,province_code
		arp.addMapping("psycity", "city_code,country_code,province_code", Psycity.class);
		arp.addMapping("psyknowledge", "psyknowledge_id", Psyknowledge.class);
		// Composite Primary Key order: oper_traceno,opera_flag,opera_time,opera_type
		arp.addMapping("psyopehis", "oper_traceno,opera_flag,opera_time,opera_type", Psyopehis.class);
		arp.addMapping("psytest", "psytests_id", Psytest.class);
		// Composite Primary Key order: victim_id,victimtest_id
		arp.addMapping("psytestinfo", "victim_id,victimtest_id", Psytestinfo.class);
		arp.addMapping("rescueknowledge", "rescueknowledge_id", Rescueknowledge.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("victiminfo", "victim_id", Victiminfo.class);
		arp.addMapping("volunteerinfo", "volunteer_id", Volunteerinfo.class);
	}
}

