package com.boc.model;

import com.boc.model.base.BaseDoctorinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Doctorinfo extends BaseDoctorinfo<Doctorinfo> {
	public static final Doctorinfo dao = new Doctorinfo().dao();
}
