package com.boc.model;

import com.boc.model.base.BasePsycity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Psycity extends BasePsycity<Psycity> {
	public static final Psycity dao = new Psycity().dao();
}
