package com.boc.model;

import com.boc.model.base.BasePsyknowledge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Psyknowledge extends BasePsyknowledge<Psyknowledge> {
	public static final Psyknowledge dao = new Psyknowledge().dao();
}
