package com.boc.model;

import com.boc.model.base.BasePsyopehis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Psyopehis extends BasePsyopehis<Psyopehis> {
	public static final Psyopehis dao = new Psyopehis().dao();
}
