package com.boc.model;

import com.boc.model.base.BasePsytestinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Psytestinfo extends BasePsytestinfo<Psytestinfo> {
	public static final Psytestinfo dao = new Psytestinfo().dao();
}
