package com.boc.model;

import com.boc.model.base.BasePsytest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Psytest extends BasePsytest<Psytest> {
	public static final Psytest dao = new Psytest().dao();
}
