package com.boc.model;

import com.boc.model.base.BaseRescueknowledge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rescueknowledge extends BaseRescueknowledge<Rescueknowledge> {
	public static final Rescueknowledge dao = new Rescueknowledge().dao();
}
