package com.boc.model;

import com.boc.model.base.BaseVictiminfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Victiminfo extends BaseVictiminfo<Victiminfo> {
	public static final Victiminfo dao = new Victiminfo().dao();
}
