package com.boc.model;

import com.boc.model.base.BaseVolunteerinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Volunteerinfo extends BaseVolunteerinfo<Volunteerinfo> {
	public static final Volunteerinfo dao = new Volunteerinfo().dao();
}
