package com.bocsoft.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDoctorInfo<M extends BaseDoctorInfo<M>> extends Model<M> implements IBean {

    /**
     * 医师ID
     */
    public M setDoctorId(java.lang.String doctorId) {
        set("doctor_id", doctorId);
        return (M)this;
    }

    /**
     * 医师ID
     */
    public java.lang.String getDoctorId() {
        return getStr("doctor_id");
    }

    /**
     * 医师姓名
     */
    public M setDoctorName(java.lang.String doctorName) {
        set("doctor_name", doctorName);
        return (M)this;
    }

    /**
     * 医师姓名
     */
    public java.lang.String getDoctorName() {
        return getStr("doctor_name");
    }

    /**
     * "性别F-女M-男"
     */
    public M setDoctorGender(java.lang.String doctorGender) {
        set("doctor_gender", doctorGender);
        return (M)this;
    }

    /**
     * "性别F-女M-男"
     */
    public java.lang.String getDoctorGender() {
        return getStr("doctor_gender");
    }

    /**
     * 医师证件类型
     */
    public M setDoctorCertype(java.lang.String doctorCertype) {
        set("doctor_certype", doctorCertype);
        return (M)this;
    }

    /**
     * 医师证件类型
     */
    public java.lang.String getDoctorCertype() {
        return getStr("doctor_certype");
    }

    /**
     * 医师证件号码
     */
    public M setDoctorCertno(java.lang.String doctorCertno) {
        set("doctor_certno", doctorCertno);
        return (M)this;
    }

    /**
     * 医师证件号码
     */
    public java.lang.String getDoctorCertno() {
        return getStr("doctor_certno");
    }

    /**
     * 医师执业资格证号
     */
    public M setCertificate(java.lang.String certificate) {
        set("certificate", certificate);
        return (M)this;
    }

    /**
     * 医师执业资格证号
     */
    public java.lang.String getCertificate() {
        return getStr("certificate");
    }

    /**
     * 医师所在地区
     */
    public M setAddressCode(java.lang.String addressCode) {
        set("address_code", addressCode);
        return (M)this;
    }

    /**
     * 医师所在地区
     */
    public java.lang.String getAddressCode() {
        return getStr("address_code");
    }

    /**
     * 医师所在单位
     */
    public M setAffiliate(java.lang.String affiliate) {
        set("affiliate", affiliate);
        return (M)this;
    }

    /**
     * 医师所在单位
     */
    public java.lang.String getAffiliate() {
        return getStr("affiliate");
    }

    /**
     * 医师掌握心理知识大类
     */
    public M setPsyledgeType(java.lang.String psyledgeType) {
        set("psyledge_type", psyledgeType);
        return (M)this;
    }

    /**
     * 医师掌握心理知识大类
     */
    public java.lang.String getPsyledgeType() {
        return getStr("psyledge_type");
    }

    /**
     * 医师掌握心理知识小类
     */
    public M setPsyledgeSubtype(java.lang.String psyledgeSubtype) {
        set("psyledge_subtype", psyledgeSubtype);
        return (M)this;
    }

    /**
     * 医师掌握心理知识小类
     */
    public java.lang.String getPsyledgeSubtype() {
        return getStr("psyledge_subtype");
    }

    /**
     * 医师掌握心理测评知识大类
     */
    public M setPsytestsType(java.lang.String psytestsType) {
        set("psytests_type", psytestsType);
        return (M)this;
    }

    /**
     * 医师掌握心理测评知识大类
     */
    public java.lang.String getPsytestsType() {
        return getStr("psytests_type");
    }

    /**
     * 医师掌握心理测评知识小类
     */
    public M setPsytestsSubtype(java.lang.String psytestsSubtype) {
        set("psytests_subtype", psytestsSubtype);
        return (M)this;
    }

    /**
     * 医师掌握心理测评知识小类
     */
    public java.lang.String getPsytestsSubtype() {
        return getStr("psytests_subtype");
    }

    /**
     * "当前是否参与辅导Y-是N-否"
     */
    public M setCounseling(java.lang.String counseling) {
        set("counseling", counseling);
        return (M)this;
    }

    /**
     * "当前是否参与辅导Y-是N-否"
     */
    public java.lang.String getCounseling() {
        return getStr("counseling");
    }

    /**
     * 当前辅导数
     */
    public M setCounselingNum(java.lang.String counselingNum) {
        set("counseling_num", counselingNum);
        return (M)this;
    }

    /**
     * 当前辅导数
     */
    public java.lang.String getCounselingNum() {
        return getStr("counseling_num");
    }

    /**
     * "医师总体满意度W-WONDERFUL 非常满意G-GOOD      基本满意Y-YAWP      不满意"
     */
    public M setSatisficing(java.lang.String satisficing) {
        set("satisficing", satisficing);
        return (M)this;
    }

    /**
     * "医师总体满意度W-WONDERFUL 非常满意G-GOOD      基本满意Y-YAWP      不满意"
     */
    public java.lang.String getSatisficing() {
        return getStr("satisficing");
    }

    /**
     * 备注1
     */
    public M setReserved1(java.lang.String reserved1) {
        set("reserved1", reserved1);
        return (M)this;
    }

    /**
     * 备注1
     */
    public java.lang.String getReserved1() {
        return getStr("reserved1");
    }

    /**
     * 备注2
     */
    public M setReserved2(java.lang.String reserved2) {
        set("reserved2", reserved2);
        return (M)this;
    }

    /**
     * 备注2
     */
    public java.lang.String getReserved2() {
        return getStr("reserved2");
    }

    /**
     * 备注3
     */
    public M setReserved3(java.lang.String reserved3) {
        set("reserved3", reserved3);
        return (M)this;
    }

    /**
     * 备注3
     */
    public java.lang.String getReserved3() {
        return getStr("reserved3");
    }

    /**
     * 备注4
     */
    public M setReserved4(java.lang.String reserved4) {
        set("reserved4", reserved4);
        return (M)this;
    }

    /**
     * 备注4
     */
    public java.lang.String getReserved4() {
        return getStr("reserved4");
    }

}

