package com.bocsoft.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVictiminfo<M extends BaseVictiminfo<M>> extends Model<M> implements IBean {

    /**
     * 受灾群众ID （物联网设备读取ID、基本信息主动录入时系统自动生成ID）
     */
    public M setVictimId(java.lang.String victimId) {
        set("victim_id", victimId);
        return (M) this;
    }

    /**
     * 受灾群众ID （物联网设备读取ID、基本信息主动录入时系统自动生成ID）
     */
    public java.lang.String getVictimId() {
        return getStr("victim_id");
    }

    /**
     * 姓名
     */
    public M setVictimName(java.lang.String victimName) {
        set("victim_name", victimName);
        return (M) this;
    }

    /**
     * 姓名
     */
    public java.lang.String getVictimName() {
        return getStr("victim_name");
    }

    /**
     * 性别F-女,M-男
     */
    public M setVictimGender(java.lang.String victimGender) {
        set("victim_gender", victimGender);
        return (M) this;
    }

    /**
     * 性别F-女,M-男
     */
    public java.lang.String getVictimGender() {
        return getStr("victim_gender");
    }

    /**
     * 证件类型
     */
    public M setVictimCertype(java.lang.String victimCertype) {
        set("victim_certype", victimCertype);
        return (M) this;
    }

    /**
     * 证件类型
     */
    public java.lang.String getVictimCertype() {
        return getStr("victim_certype");
    }

    /**
     * 证件号码
     */
    public M setVictimCertno(java.lang.String victimCertno) {
        set("victim_certno", victimCertno);
        return (M) this;
    }

    /**
     * 证件号码
     */
    public java.lang.String getVictimCertno() {
        return getStr("victim_certno");
    }

    /**
     * 联系方式
     */
    public M setVictimPhone(java.lang.String victimPhone) {
        set("victim_phone", victimPhone);
        return (M) this;
    }

    /**
     * 联系方式
     */
    public java.lang.String getVictimPhone() {
        return getStr("victim_phone");
    }

    /**
     * 所在地区
     */
    public M setAddressCode(java.lang.String addressCode) {
        set("address_code", addressCode);
        return (M) this;
    }

    /**
     * 所在地区
     */
    public java.lang.String getAddressCode() {
        return getStr("address_code");
    }

    /**
     * 详细地址
     */
    public M setAddressDetail(java.lang.String addressDetail) {
        set("address_detail", addressDetail);
        return (M) this;
    }

    /**
     * 详细地址
     */
    public java.lang.String getAddressDetail() {
        return getStr("address_detail");
    }

    /**
     * 是否主动登记 Y-是N-否
     */
    public M setRegisterFlag(java.lang.String registerFlag) {
        set("register_flag", registerFlag);
        return (M) this;
    }

    /**
     * 是否主动登记 Y-是N-否
     */
    public java.lang.String getRegisterFlag() {
        return getStr("register_flag");
    }

    /**
     * 是否寻求救援知识Y-是N-否
     */
    public M setSerchRescue(java.lang.String serchRescue) {
        set("serch_rescue", serchRescue);
        return (M) this;
    }

    /**
     * 是否寻求救援知识Y-是N-否
     */
    public java.lang.String getSerchRescue() {
        return getStr("serch_rescue");
    }

    /**
     * 救援知识库号
     */
    public M setRescueKnowledgeid(java.lang.String rescueKnowledgeid) {
        set("rescue_knowledgeid", rescueKnowledgeid);
        return (M) this;
    }

    /**
     * 救援知识库号
     */
    public java.lang.String getRescueKnowledgeid() {
        return getStr("rescue_knowledgeid");
    }

    /**
     * 是否寻求心理知识Y-是N-否
     */
    public M setSerchPsy(java.lang.String serchPsy) {
        set("serch_psy", serchPsy);
        return (M) this;
    }

    /**
     * 是否寻求心理知识Y-是N-否
     */
    public java.lang.String getSerchPsy() {
        return getStr("serch_psy");
    }

    /**
     * 心理知识库号
     */
    public M setPsyKnowledgeid(java.lang.String psyKnowledgeid) {
        set("psy_knowledgeid", psyKnowledgeid);
        return (M) this;
    }

    /**
     * 心理知识库号
     */
    public java.lang.String getPsyKnowledgeid() {
        return getStr("psy_knowledgeid");
    }

    /**
     * 是否参与心理测评Y-是N-否
     */
    public M setJoinPsyflag(java.lang.String joinPsyflag) {
        set("join_psyflag", joinPsyflag);
        return (M) this;
    }

    /**
     * 是否参与心理测评Y-是N-否
     */
    public java.lang.String getJoinPsyflag() {
        return getStr("join_psyflag");
    }

    /**
     * 心理测评号
     */
    public M setPsytestsId(java.lang.String psytestsId) {
        set("psytests_id", psytestsId);
        return (M) this;
    }

    /**
     * 心理测评号
     */
    public java.lang.String getPsytestsId() {
        return getStr("psytests_id");
    }

    /**
     * "当前心理测评等级H-HEALTH健康状态U-UNHEALTH不良状态 B-BOLCK心理障碍I-ILLNESS心理疾病"
     */
    public M setTestsLevel(java.lang.String testsLevel) {
        set("tests_level", testsLevel);
        return (M) this;
    }

    /**
     * "当前心理测评等级H-HEALTH健康状态U-UNHEALTH不良状态 B-BOLCK心理障碍I-ILLNESS心理疾病"
     */
    public java.lang.String getTestsLevel() {
        return getStr("tests_level");
    }

    /**
     * "当前是否接受辅导Y-是N-否"
     */
    public M setHelpFlag(java.lang.String helpFlag) {
        set("help_flag", helpFlag);
        return (M) this;
    }

    /**
     * "当前是否接受辅导Y-是N-否"
     */
    public java.lang.String getHelpFlag() {
        return getStr("help_flag");
    }

    /**
     * 当前辅导医师ID
     */
    public M setPsychologistId(java.lang.String psychologistId) {
        set("psychologist_id", psychologistId);
        return (M) this;
    }

    /**
     * 当前辅导医师ID
     */
    public java.lang.String getPsychologistId() {
        return getStr("psychologist_id");
    }

    /**
     * 当前辅导志愿者ID
     */
    public M setVolunteerId(java.lang.String volunteerId) {
        set("volunteer_id", volunteerId);
        return (M) this;
    }

    /**
     * 当前辅导志愿者ID
     */
    public java.lang.String getVolunteerId() {
        return getStr("volunteer_id");
    }

    /**
     * 登记日期
     */
    public M setRegisterDate(java.lang.String registerDate) {
        set("register_date", registerDate);
        return (M) this;
    }

    /**
     * 登记日期
     */
    public java.lang.String getRegisterDate() {
        return getStr("register_date");
    }

    /**
     * 备注
     */
    public M setAdded(java.lang.String added) {
        set("added", added);
        return (M) this;
    }

    /**
     * 备注
     */
    public java.lang.String getAdded() {
        return getStr("added");
    }

    /**
     * 备用1
     */
    public M setReserved1(java.lang.String reserved1) {
        set("reserved1", reserved1);
        return (M) this;
    }

    /**
     * 备用1
     */
    public java.lang.String getReserved1() {
        return getStr("reserved1");
    }

    /**
     * 备用2
     */
    public M setReserved2(java.lang.String reserved2) {
        set("reserved2", reserved2);
        return (M) this;
    }

    /**
     * 备用2
     */
    public java.lang.String getReserved2() {
        return getStr("reserved2");
    }

    /**
     * 备用2
     */
    public M setTestJoinDate(String testJoinDate) {
        set("testioin_date", testJoinDate);
        return (M) this;
    }

    /**
     * 备用2
     */
    public String getTestJoinDate() {
        return getStr("testioin_date");
    }

    /**
     * 备用2
     */
    public M setVictimAge(String victimAge) {
        set("victim_age", victimAge);
        return (M) this;
    }

    /**
     * 备用2
     */
    public String getVictimAge() {
        return getStr("victim_age");
    }

    /**
     * 备用2
     */
    public M setReceiveType(String receiveType) {
        set("receive_type", receiveType);
        return (M) this;
    }

    /**
     * 备用2
     */
    public String getReceiveType() {
        return getStr("receive_type");
    }
}