package com.bocsoft.common.model;

import com.bocsoft.common.model.base.BaseDataDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataDictionary extends BaseDataDictionary<DataDictionary> {

}
