package com.bocsoft.common.model;

import com.bocsoft.common.model.base.BaseDoctorInfo;

import javax.print.Doc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoctorInfo extends BaseDoctorInfo<DoctorInfo> {
    public final static DoctorInfo dao = new DoctorInfo().dao();

}
