package com.bocsoft.common.model;

import com.bocsoft.common.model.base.BaseFileUploaded;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileUploaded extends BaseFileUploaded<FileUploaded> {
    public final static FileUploaded dao = new FileUploaded().dao();
}
