package com.bocsoft.common.model;

import com.bocsoft.common.model.base.BaseSysFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFunction extends BaseSysFunction<SysFunction> {

}
