package com.bocsoft.common.model;

import com.bocsoft.common.model.base.BaseSysRoleFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleFunction extends BaseSysRoleFunction<SysRoleFunction> {

}
