package com.bocsoft.common.model;

import com.bocsoft.common.model.base.BaseUploadInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadInfo extends BaseUploadInfo<UploadInfo> {
    public static  final  UploadInfo dao = new UploadInfo().dao();
}
