package com.boc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePsytest<M extends BasePsytest<M>> extends Model<M> implements IBean {

	/**
	 * 心理测评知识库号
	 */
	public M setPsytestsId(java.lang.String psytestsId) {
		set("psytests_id", psytestsId);
		return (M)this;
	}
	
	/**
	 * 心理测评知识库号
	 */
	public java.lang.String getPsytestsId() {
		return getStr("psytests_id");
	}

	/**
	 * 心理测评大类
	 */
	public M setPsytestsType(java.lang.String psytestsType) {
		set("psytests_type", psytestsType);
		return (M)this;
	}
	
	/**
	 * 心理测评大类
	 */
	public java.lang.String getPsytestsType() {
		return getStr("psytests_type");
	}

	/**
	 * 心理测评小类
	 */
	public M setPsytestsSubtype(java.lang.String psytestsSubtype) {
		set("psytests_subtype", psytestsSubtype);
		return (M)this;
	}
	
	/**
	 * 心理测评小类
	 */
	public java.lang.String getPsytestsSubtype() {
		return getStr("psytests_subtype");
	}

	/**
	 * 心理测评详情
	 */
	public M setPsytestsDetail(java.lang.String psytestsDetail) {
		set("psytests_detail", psytestsDetail);
		return (M)this;
	}
	
	/**
	 * 心理测评详情
	 */
	public java.lang.String getPsytestsDetail() {
		return getStr("psytests_detail");
	}

	/**
	 * 备注1
	 */
	public M setReserved1(java.lang.String reserved1) {
		set("reserved1", reserved1);
		return (M)this;
	}
	
	/**
	 * 备注1
	 */
	public java.lang.String getReserved1() {
		return getStr("reserved1");
	}

	/**
	 * 备注2
	 */
	public M setReserved2(java.lang.String reserved2) {
		set("reserved2", reserved2);
		return (M)this;
	}
	
	/**
	 * 备注2
	 */
	public java.lang.String getReserved2() {
		return getStr("reserved2");
	}

	/**
	 * 备注3
	 */
	public M setReserved3(java.lang.String reserved3) {
		set("reserved3", reserved3);
		return (M)this;
	}
	
	/**
	 * 备注3
	 */
	public java.lang.String getReserved3() {
		return getStr("reserved3");
	}

	/**
	 * 备注4
	 */
	public M setReserved4(java.lang.String reserved4) {
		set("reserved4", reserved4);
		return (M)this;
	}
	
	/**
	 * 备注4
	 */
	public java.lang.String getReserved4() {
		return getStr("reserved4");
	}

}
