package com.boc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePsycity<M extends BasePsycity<M>> extends Model<M> implements IBean {

	/**
	 * 国家编码
	 */
	public M setCountryCode(java.lang.String countryCode) {
		set("country_code", countryCode);
		return (M)this;
	}
	
	/**
	 * 国家编码
	 */
	public java.lang.String getCountryCode() {
		return getStr("country_code");
	}

	/**
	 * 省编码
	 */
	public M setProvinceCode(java.lang.String provinceCode) {
		set("province_code", provinceCode);
		return (M)this;
	}
	
	/**
	 * 省编码
	 */
	public java.lang.String getProvinceCode() {
		return getStr("province_code");
	}

	/**
	 * 地级市编码
	 */
	public M setCityCode(java.lang.String cityCode) {
		set("city_code", cityCode);
		return (M)this;
	}
	
	/**
	 * 地级市编码
	 */
	public java.lang.String getCityCode() {
		return getStr("city_code");
	}

	/**
	 * 省名称
	 */
	public M setProvinceName(java.lang.String provinceName) {
		set("province_name", provinceName);
		return (M)this;
	}
	
	/**
	 * 省名称
	 */
	public java.lang.String getProvinceName() {
		return getStr("province_name");
	}

	/**
	 * 地级市名称
	 */
	public M setCityName(java.lang.String cityName) {
		set("city_name", cityName);
		return (M)this;
	}
	
	/**
	 * 地级市名称
	 */
	public java.lang.String getCityName() {
		return getStr("city_name");
	}

	/**
	 * "地级市状态H-预警S-正常"
	 */
	public M setCityState(java.lang.String cityState) {
		set("city_state", cityState);
		return (M)this;
	}
	
	/**
	 * "地级市状态H-预警S-正常"
	 */
	public java.lang.String getCityState() {
		return getStr("city_state");
	}

	/**
	 * 地区编号（唯一）
	 */
	public M setAddressCode(java.lang.String addressCode) {
		set("address_code", addressCode);
		return (M)this;
	}
	
	/**
	 * 地区编号（唯一）
	 */
	public java.lang.String getAddressCode() {
		return getStr("address_code");
	}

	/**
	 * 地区灾难类型
	 */
	public M setDisasterType(java.lang.String disasterType) {
		set("disaster_type", disasterType);
		return (M)this;
	}
	
	/**
	 * 地区灾难类型
	 */
	public java.lang.String getDisasterType() {
		return getStr("disaster_type");
	}

	/**
	 * 备用1
	 */
	public M setReserved1(java.lang.String reserved1) {
		set("reserved1", reserved1);
		return (M)this;
	}
	
	/**
	 * 备用1
	 */
	public java.lang.String getReserved1() {
		return getStr("reserved1");
	}

	/**
	 * 备用2
	 */
	public M setReserved2(java.lang.String reserved2) {
		set("reserved2", reserved2);
		return (M)this;
	}
	
	/**
	 * 备用2
	 */
	public java.lang.String getReserved2() {
		return getStr("reserved2");
	}

	/**
	 * 备用3
	 */
	public M setReserved3(java.lang.String reserved3) {
		set("reserved3", reserved3);
		return (M)this;
	}
	
	/**
	 * 备用3
	 */
	public java.lang.String getReserved3() {
		return getStr("reserved3");
	}

	/**
	 * 备用4
	 */
	public M setReserved4(java.lang.String reserved4) {
		set("reserved4", reserved4);
		return (M)this;
	}
	
	/**
	 * 备用4
	 */
	public java.lang.String getReserved4() {
		return getStr("reserved4");
	}

}
