package com.boc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePsytestinfo<M extends BasePsytestinfo<M>> extends Model<M> implements IBean {

	/**
	 * 心理测评号
	 */
	public M setVictimtestId(java.lang.String victimtestId) {
		set("victimtest_id", victimtestId);
		return (M)this;
	}
	
	/**
	 * 心理测评号
	 */
	public java.lang.String getVictimtestId() {
		return getStr("victimtest_id");
	}

	/**
	 * 受灾群众ID
	 */
	public M setVictimId(java.lang.String victimId) {
		set("victim_id", victimId);
		return (M)this;
	}
	
	/**
	 * 受灾群众ID
	 */
	public java.lang.String getVictimId() {
		return getStr("victim_id");
	}

	/**
	 * 心理测评知识库号
	 */
	public M setPsytestsId(java.lang.String psytestsId) {
		set("psytests_id", psytestsId);
		return (M)this;
	}
	
	/**
	 * 心理测评知识库号
	 */
	public java.lang.String getPsytestsId() {
		return getStr("psytests_id");
	}

	/**
	 * "心理测评等级H-HEALTH健康状态U-UNHEALTH不良状态 B-BOLCK心理障碍I-ILLNESS心理疾病"
	 */
	public M setTestsLevel(java.lang.String testsLevel) {
		set("tests_level", testsLevel);
		return (M)this;
	}
	
	/**
	 * "心理测评等级H-HEALTH健康状态U-UNHEALTH不良状态 B-BOLCK心理障碍I-ILLNESS心理疾病"
	 */
	public java.lang.String getTestsLevel() {
		return getStr("tests_level");
	}

	/**
	 * 当前辅导医师ID
	 */
	public M setPsychologistId(java.lang.String psychologistId) {
		set("psychologist_id", psychologistId);
		return (M)this;
	}
	
	/**
	 * 当前辅导医师ID
	 */
	public java.lang.String getPsychologistId() {
		return getStr("psychologist_id");
	}

	/**
	 * 当前辅导志愿者ID
	 */
	public M setVolunteerId(java.lang.String volunteerId) {
		set("volunteer_id", volunteerId);
		return (M)this;
	}
	
	/**
	 * 当前辅导志愿者ID
	 */
	public java.lang.String getVolunteerId() {
		return getStr("volunteer_id");
	}

	/**
	 * 参与测评日期
	 */
	public M setTestioinDate(java.lang.String testioinDate) {
		set("testioin_date", testioinDate);
		return (M)this;
	}
	
	/**
	 * 参与测评日期
	 */
	public java.lang.String getTestioinDate() {
		return getStr("testioin_date");
	}

	/**
	 * 参与测评时间
	 */
	public M setTestjoinTime(java.lang.String testjoinTime) {
		set("testjoin_time", testjoinTime);
		return (M)this;
	}
	
	/**
	 * 参与测评时间
	 */
	public java.lang.String getTestjoinTime() {
		return getStr("testjoin_time");
	}

	/**
	 * 参与测评所在地区
	 */
	public M setAddressCode(java.lang.String addressCode) {
		set("address_code", addressCode);
		return (M)this;
	}
	
	/**
	 * 参与测评所在地区
	 */
	public java.lang.String getAddressCode() {
		return getStr("address_code");
	}

	/**
	 * "当前是否参与辅导Y-是N-否"
	 */
	public M setCounseling(java.lang.String counseling) {
		set("counseling", counseling);
		return (M)this;
	}
	
	/**
	 * "当前是否参与辅导Y-是N-否"
	 */
	public java.lang.String getCounseling() {
		return getStr("counseling");
	}

	/**
	 * "当前辅导满意度W-WONDERFUL 非常满意G-GOOD      基本满意Y-YAWP      不满意"
	 */
	public M setSatisficing(java.lang.String satisficing) {
		set("satisficing", satisficing);
		return (M)this;
	}
	
	/**
	 * "当前辅导满意度W-WONDERFUL 非常满意G-GOOD      基本满意Y-YAWP      不满意"
	 */
	public java.lang.String getSatisficing() {
		return getStr("satisficing");
	}

	/**
	 * 备注
	 */
	public M setAdded(java.lang.String added) {
		set("added", added);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getAdded() {
		return getStr("added");
	}

	/**
	 * 备用1
	 */
	public M setReserved1(java.lang.String reserved1) {
		set("reserved1", reserved1);
		return (M)this;
	}
	
	/**
	 * 备用1
	 */
	public java.lang.String getReserved1() {
		return getStr("reserved1");
	}

	/**
	 * 备用2
	 */
	public M setReserved2(java.lang.String reserved2) {
		set("reserved2", reserved2);
		return (M)this;
	}
	
	/**
	 * 备用2
	 */
	public java.lang.String getReserved2() {
		return getStr("reserved2");
	}

	/**
	 * 备用3
	 */
	public M setReserved3(java.lang.String reserved3) {
		set("reserved3", reserved3);
		return (M)this;
	}
	
	/**
	 * 备用3
	 */
	public java.lang.String getReserved3() {
		return getStr("reserved3");
	}

	/**
	 * 备用4
	 */
	public M setReserved4(java.lang.String reserved4) {
		set("reserved4", reserved4);
		return (M)this;
	}
	
	/**
	 * 备用4
	 */
	public java.lang.String getReserved4() {
		return getStr("reserved4");
	}

}
